### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by SiEncan** [CodeDotJS/instagram-profile-picture#5]
TypeError: Cannot read property 'split' of undefined
    at got.then.res (/rbd/pnpm-volume/e938c313-b179-4233-a6ea-97b896d1f21d/node_modules/.registry.npmjs.org/instagram-profile-picture/1.0.5/node_modules/instagram-profile-picture/index.js:50:54)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by CodeDotJS** [comment]
Please check ~ https://github.com/CodeDotJS/instagram-profile-picture/issues/4
